// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkPtysjodxh356vyuQSaAhg59xjeHjMVU',
    appId: '1:346631879936:web:52a3c48ecb017e14ec47e5',
    messagingSenderId: '346631879936',
    projectId: 'smart-drying-iot',
    authDomain: 'smart-drying-iot.firebaseapp.com',
    databaseURL: 'https://smart-drying-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-drying-iot.firebasestorage.app',
    measurementId: 'G-TKD1THSSJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF6qh928QqLNNHXKZ2My1kP7FtefxggmY',
    appId: '1:346631879936:android:de955d5384477ae0ec47e5',
    messagingSenderId: '346631879936',
    projectId: 'smart-drying-iot',
    databaseURL: 'https://smart-drying-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-drying-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4gfV9-frj8zDygDJ3GJ1oM08QCyiaZQ0',
    appId: '1:346631879936:ios:bb8f5ca55acaf79fec47e5',
    messagingSenderId: '346631879936',
    projectId: 'smart-drying-iot',
    databaseURL: 'https://smart-drying-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-drying-iot.firebasestorage.app',
    androidClientId: '346631879936-3sruv8mnlungu3o6lvs52gom5u64ut0n.apps.googleusercontent.com',
    iosClientId: '346631879936-8fvnaa6vphi182mib06qjb1b0kovblos.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4gfV9-frj8zDygDJ3GJ1oM08QCyiaZQ0',
    appId: '1:346631879936:ios:bb8f5ca55acaf79fec47e5',
    messagingSenderId: '346631879936',
    projectId: 'smart-drying-iot',
    databaseURL: 'https://smart-drying-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-drying-iot.firebasestorage.app',
    androidClientId: '346631879936-3sruv8mnlungu3o6lvs52gom5u64ut0n.apps.googleusercontent.com',
    iosClientId: '346631879936-8fvnaa6vphi182mib06qjb1b0kovblos.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkPtysjodxh356vyuQSaAhg59xjeHjMVU',
    appId: '1:346631879936:web:68a4aac52a9d749cec47e5',
    messagingSenderId: '346631879936',
    projectId: 'smart-drying-iot',
    authDomain: 'smart-drying-iot.firebaseapp.com',
    databaseURL: 'https://smart-drying-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-drying-iot.firebasestorage.app',
    measurementId: 'G-J34KYQEFD4',
  );
}
